### ISSUE TITLE
Suricata 7.0.7

### ISSUE THREAD

**Issue by ehnwebmaster** [matt-culbert/suricata_rules#1]
Hello,

Thank you for the script now I'm able to report Suricata to service AbuseIPDB

Just noticed Suricata update to current version;

`echo "Downloading and unpacking Suricata 7.0.7"
wget https://github.com/OISF/suricata/archive/refs/tags/suricata-7.0.7.tar.gz 
mkdir suricata
tar -xzvf suricata-7.0.7.tar.gz -C suricata --strip-components 1`

But any time I've reboot Suricata.yaml reconfigures to Lua support disabled 
, how can I prevent this behavior?

Thanks in advance

**Comment by ehnwebmaster** [comment]
Fixed, just discovered OPNsense uses templates, need to edit 

`/usr/local/opnsense/service/templates/OPNsense/IDS/custom.yaml`

Or

`/usr/local/opnsense/service/templates/OPNsense/IDS/suricata.yaml`

**Comment by matt-culbert** [comment]
Glad you were able to fix it :)
